### ISSUE TITLE
Package incompatibility with elm-geometry 3.0.0

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry-svg#13]
The latest version of `elm-geometry-svg` has this contraint `ianmackenzie/elm-geometry 2.0.0 <= v < 3.0.0`. This prevents me from upgrading to the latest version of `elm-geometry 3.0.0` as I use both packages.

**Comment by ianmackenzie** [comment]
Oops, forgot to update that package, sorry! I'll do that today.
